//
//  RecipeDetailInteractor.swift
//  recipinder
//
//  Created by Taufiq Widi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RecipeDetailInteractor {
}

// MARK: - Extensions -

extension RecipeDetailInteractor: RecipeDetailInteractorInterface {
}
