//
//  RecipeDetailPresenter.swift
//  recipinder
//
//  Created by Taufiq Widi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RecipeDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: RecipeDetailViewInterface
    private let interactor: RecipeDetailInteractorInterface
    private let wireframe: RecipeDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: RecipeDetailViewInterface, interactor: RecipeDetailInteractorInterface, wireframe: RecipeDetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RecipeDetailPresenter: RecipeDetailPresenterInterface {
}
