//
//  RecipeDetailViewController.swift
//  recipinder
//
//  Created by Taufiq Widi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RecipeDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RecipeDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension RecipeDetailViewController: RecipeDetailViewInterface {

}

#if DEBUG
import SwiftUI

struct RecipeDetailVCRepresentable: UIViewControllerRepresentable {
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        // leave this empty
    }

    @available(iOS 13.0.0, *)
    func makeUIViewController(context: Context) -> UIViewController {
        RecipeDetailViewController()
    }
}

@available(iOS 13.0, *)
struct RecipeDetailVCPreview: PreviewProvider {
    static var previews: some View {
        RecipeDetailVCRepresentable()
    }
}
#endif
