//
//  RecipeDetailWireframe.swift
//  recipinder
//
//  Created by Taufiq Widi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RecipeDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = RecipeDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = RecipeDetailInteractor()
        let presenter = RecipeDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RecipeDetailWireframe: RecipeDetailWireframeInterface {
}
