//
//  RecipeDetailInterfaces.swift
//  recipinder
//
//  Created by Taufiq Widi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RecipeDetailWireframeInterface: WireframeInterface {
}

protocol RecipeDetailViewInterface: ViewInterface {
}

protocol RecipeDetailPresenterInterface: PresenterInterface {
}

protocol RecipeDetailInteractorInterface: InteractorInterface {
}
